### ISSUE TITLE
Dedupable device on NFS appliance fails to recycle purged volume

### ISSUE THREAD

**Issue by rosowiecki** [bareos/bareos#2393]
### Bareos component version

24.0.4~pre30.dd9a00734

### Steps to reproduce

Make a backup exceeding current Append volume, have a expired volume eligible for Purge

### Expected results

Volume is purged and recycled for backup, backup finishes

### Actual results

Error truncating volume, backup fails

### Environment

```markdown
Rocky Linux 9.5

volume mount:
192.168.XXX.XXX:/export/bareos_backup on /bareos/dedupable type nfs (rw,relatime,vers=3,rsize=65536,wsize=32768,namlen=255,soft,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.XXX.XXX,mountvers=3,mountport=61001,mountproto=tcp,local_lock=none,addr=192.168.XXX.XXX)
```

### Relevant log output

```shell
30	2025-10-14 22:05:48	bareos JobId 6025: Fatal error: Job 6025 canceled.
29	2025-10-14 22:05:48	bareos JobId 6025: Marking Volume "Incremental-0117" in Error in Catalog.
28	2025-10-14 22:05:48	bareos JobId 6025: Fatal error: stored/label.cc:1060 Truncate error on device "DedupStorage0002" (/bareos/dedupable): ERR=stored/dev.cc:906 Unable to close device "DedupStorage0002" (/bareos/dedupable). ERR=Success

27	2025-10-14 22:05:48	bareos: ERROR in backends/dedupable_device.cc:381 Could not delete /bareos/dedupable/Incremental-0117. ERR=Directory not empty
26	2025-10-14 22:05:48	bareos: Warning: Dedup device option warning: Blocksize was not set explicitly; set to default (4096).
25	2025-10-14 22:05:48	bareos JobId 6025: Recycled volume "Incremental-0117"
24	2025-10-14 22:05:48	bareos JobId 6025: All records pruned from Volume "Incremental-0117"; marking it "Purged"
23	2025-10-14 22:05:48	bareos JobId 6025: There are no more Jobs associated with Volume "Incremental-0117". Marking it purged.
22	2025-10-14 22:05:48	bareos JobId 6025: Purging the following 8 JobIds: 4431,4433,4435,4437,4430,4432,4434,4436
21	2025-10-14 22:05:48	bareos JobId 6025: Volume "Incremental-0117" has Volume Retention of 2592000 sec. and has 8 jobs that will be pruned
20	2025-10-14 22:05:47	bareos JobId 6025: End of medium on Volume "Incremental-0066" Bytes=4,294,279,225 Blocks=4,099 at 14-Oct-2025 22:05.
```

### Relevant traces output

```shell

```

### Anything else?

My NFS experts believe that there are not closed removed files with hidden .nfsXXXXXXX name at step 27, which could mean purge operation doesn't close file handles properly

**Comment by sebsura** [comment]
The directory is removed so that the normal setup code can completely recreate the directory.  Its probably possible to skip deleting the directory, but if the problem is indeed that some file handles are not closed, then we should fix that instead.

**Comment by rosowiecki** [comment]
A hint that could be helpful: when backup was started on already purged volume, it was recycled with no problem.

As a workaround I'll probably purge volumes manually or by some cron job.

**Comment by rosowiecki** [comment]
Wit pool settings: AutoPrune=no Recycle=yes and cron job for pruning, situation is slightly better (no failed backups), but I still get truncated volumes with "Error" status; I guess recycling sometimes fails, but without failing backup job.

**Comment by rosowiecki** [comment]
may be related: bareos-sd of this storage recently failed due to filedescriptor leak

**Comment by rosowiecki** [comment]
FYI: CIFS filesystem on the same appliance causes no problems with volume purging.

**Comment by sebsura** [comment]
Are you still on 24.0.4 or did you update to 25 already ?

**Comment by sebsura** [comment]
I also created the backports #2549  (bareos-25), #2550 (bareos-24) and #2551 (bareos-23), so feel free to pick the version that matches your director.
